### ISSUE TITLE
Support for plex pass

### ISSUE THREAD

**Issue by jkaberg** [wernight/docker-plex-media-server#3] opened 2015-11-01 16:35 UTC
There's an update script [here](https://github.com/mrworf/plexupdate) that supports plex pass.

Auto update on container start-up would be nice aswell, opt-in ofcourse (via arg or so)

**Comment by Gelioks** [comment] 2015-11-05 12:42
+1 thank you

**Comment by wernight** [comment] 2015-11-08 09:25
On Plex update it's possible to:
1. and/or update the image (already done)
2. and/or retrieves the latest version when it's started (however the provided script requires `root` so priviledges must be dropped later and users cannot use `--user` flag)
3. and/or support plex upgrade (possibly using [`runit`](http://smarden.org/runit/) which would also solve the [PID 1 zombie reaping problem](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/))

As long as people don't always start from the container all sounds a decent improvements during ugprdes.

As for **Plex Pass**, I think it's also very much related:
- Solution (1) is harder and not sure if allowed,
- Solution (2) has the `root` issue.
- Solution (3) sounds the best, but requires more work to understand what Plex requires to be able to do that.

**Comment by jkaberg** [comment] 2015-11-08 15:44
@wernight I was under the assumption that "plex upgrade" only works on Windows hosts?

**Comment by wernight** [comment] 2015-11-09 08:45
@jkaberg Normally it does work also on Linux but it might be from package manager.

**Comment by wernight** [comment] 2015-11-19 20:31
About your PR:
- https://tools.linuxserver.io/latest-plex.json doesn't seem to be an official channel, may be I'm wrong, but I think there are way to get the premium binary without that.
- You install `dbus` `gdebi-core` and `avahi-daemon`, can you explain why you need those?
- You want to switch `dpkg` to `gdebi` which from what I see has more issues, why this change?

Regarding the Plex Pass, I think the best would be two tags, one premium and one non premium. It does look like `https://plex.tv/downloads?channel=plexpass` requires people to log in so it makes me wonder even more about why/how tools.linuxserver.io would be allowed to bypass that check. I've premium so I could in theory get the latest link.

This goes back to the solution of auto-updating. I'll try to bring someone from Plex to discuss it here.

**Comment by wernight** [comment] 2015-11-20 08:52
So in place auto-upgrade isn't supported on Linux by Plex. This leaves either:
- Pull image on update
- Restart container on update

Currently the first one was chosen, but it's possible to have both solutions (via environment variable) and the second solution allows Plex Pass via user/password and a bit faster update.

**Comment by wernight** [comment] 2015-11-23 09:14
Looking more into it, it's impossible to auto-update on re-create/restart as we're not running as root (by purpose). It'd be possible to run as root and drop privileges but that would break `--user=USER` Docker flag and users relying on it.

Both versions seem to be identical most of the time but I'll definitely look into supporting the Pass version one way or another.

What [`plexupdate.sh`](https://raw.githubusercontent.com/mrworf/plexupdate/master/plexupdate.sh) does is very close to the current, it simply uses `https://plex.tv/downloads?channel=plexpass` and post PlexPass authentication form data.

**Comment by wernight** [comment] 2015-11-23 11:03
See also https://forums.plex.tv/discussion/195263/premium-download-link

**Comment by jkaberg** [comment] 2015-11-24 19:42
The most convenient approach would of course be to upgrade on container start, however that (as you pointed out) does require root permissions. 

I personally will strive to achieve this, but I understand your reasons for not doing so.

**Comment by jkaberg** [comment] 2015-11-27 19:39
Perhaps something like this for auto updating @wernight, https://github.com/aptalca/docker-plexrequests/blob/master/firstrun.sh

**Comment by wernight** [comment] 2015-11-28 00:41
The PlexPass is frequently identical to the public but gets updated slightly earlier. This means that only people caring to get the very latest ASAP would really want this.

Therefor, I'll change so that there is another branch that auto-update on start, running as root initially, for people who prefer latest over slightly faster/secure,

**Comment by wernight** [comment] 2015-12-02 13:23
Fixed by having a branch that runs the really latest on each start, supporting PlexPass users. It's still safe, and it's for users who want the really latest without disrupting users who want the simpler/more version controlled.

@jkaberg You should like that it does what you're trying to get.

See latest README for details.

**Closed as completed by wernight** 2015-12-02 13:23 UTC

**Comment by wernight** [comment] 2015-12-17 08:46
I just cannot reproduce this issue via `docker restart ...`. So weird.

**Comment by jkaberg** [comment] 2015-12-17 10:06
@wernight don't know your setup but mine's 

```
================================================================================
= OS/Debian information
================================================================================
Distributor ID: debian
Description: Debian GNU/Linux 7 (wheezy)
Release: 7.9
Codename: wheezy

================================================================================
= openmediavault information
================================================================================
Release: 2.1.20
Codename: Stone burner
================================================================================
= Locale
================================================================================
en_US.UTF-8

================================================================================
= System information
================================================================================
Linux dunder 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u6 x86_64 GNU/Linux
```

```
joel@dunder:~$ sudo docker -v
Docker version 1.9.1, build a34a1d5
```

**Comment by wernight** [comment] 2015-12-18 12:01
@jkaberg I could reproduce it when running Plex via `docker-compose up -d ...` but running it via docker and just doing `docker restart my-container` seems to always correctly fetch without your PR. I'll try some more.
