### ISSUE TITLE
Error starting container (first use)

### ISSUE THREAD

**Issue by jh125486** [wernight/docker-plex-media-server#7] opened 2015-12-31 18:01 UTC
I'm migrating from 'timhaak/plexpass' container because of pid restart issues.

I'm a plexpass user and this is my container start string:
`docker run -d --restart=always --name=plex -v /share/Docker/container-station-data/config/plex-config:/config -v /share/Multimedia:/media --net=host -p 32400:32400 -e PLEXPASS_LOGIN='x.x@gmail.com' -e PLEXPASS_PASSWORD='blargh' wernight/plex-media-server:autoupdate`

For now I'm using an empty /config directory (chowned to 797) till I can get plex up and migrate the DB.

Errors at:

```
Reading database ... 12673 files and directories currently installed.)
Preparing to unpack plexmediaserver.deb ...
/var/lib/dpkg/info/plexmediaserver.prerm: 9: /var/lib/dpkg/info/plexmediaserver.prerm: stop: not found
Unpacking plexmediaserver (0.9.15.0.1621-344f193) over (0.9.15.0.1621-344f193) ...
Setting up plexmediaserver (0.9.15.0.1621-344f193) ...
Processing triggers for systemd (215-17+deb8u2) ...
Processing triggers for mime-support (3.58) ...
+ unset PLEXPASS_LOGIN
+ unset PLEXPASS_PASSWORD
+ rm -f plexmediaserver.deb
runuser: System error
```

Any idea where I should start troubleshooting at?

Thanks!

**Comment by wernight** [comment] 2016-01-05 10:21
Could be a duplicate of #8, would you mind doing a docker pull and trying again?

**Comment by wernight** [comment] 2016-01-06 10:04
I'm looking at it again, and it doesn't look actually as a duplicate. `runuser: System error` looks like alien to me. Could you try also with `wernight/plex-media-server:latest` just to see what it says? It looks almost as you you mounted something where you shouldn't (like system stuff). You may also run as root to check access right (via `--user root`).

**Comment by wernight** [comment] 2016-01-13 09:59
Any update on this @jh125486 ?

**Comment by jh125486** [comment] 2016-01-14 17:08
Sorry for the late reply.

Using `:latest` version works, but `:autoupdate` does not unfortunately (even using `--user root`).

**Comment by wernight** [comment] 2016-01-15 09:34
Note: Plex is meant to run as non-root but currently only tested with the default random UID, so don't use `--user`.

It seems that `runuser` command isn't working on your machine which should mean there is something wrong with your Docker installation itself. `runuser` is the command from the [official Docker `debian`](https://hub.docker.com/_/debian) image, which should run just the same on any Linux because of Docker. May be check if you can upgrade (you should be running Docker 1.9+), or may be your file system. If you just run:

```
$ docker run --rm -it debian:jessie
$ useradd --system --uid 797 -M --shell /usr/sbin/nologin plex
$ runuser -u plex echo hello
hello
```

It should work. If it doesn't work, I'd recommend posting a bug on [Docker Debian](https://github.com/docker-library/official-images/issues).

**Comment by jh125486** [comment] 2016-01-15 16:37
So crazy, but those commands work.
I'm running Docker 1.9.1 on a Qnap NAS.

Thanks for all your help in this by the way!

**Comment by wernight** [comment] 2016-01-18 11:56
I made a small change to possibly solve the log line you see: `plexmediaserver.prerm: stop: not found`.

Just do a `docker pull wernight/plex-media-server:autoupdate` and retry, please let me know if the output changes.

**Comment by wernight** [comment] 2016-01-21 10:48
@jh125486 Could you check if it works now on your machine? I cannot reproduce locally. What's your OS by the way?

**Comment by jh125486** [comment] 2016-01-22 02:37
Sorry, I will as soon as I can.  During a storage pool expansion my volume became ‘inactive’, so I currently have a support request in to find out where my 16tb of data went :(
As soon as things get back to normal I’ll test the new commit.

V/r
Jacob Hochstetler

**Comment by jh125486** [comment] 2016-02-26 22:50
Ok, NAS is back up.
I pulled the new `autoupdate` version, and I'm still having the same `runuser: System error`.
This is so weird.

**Comment by wernight** [comment] 2016-02-28 11:31
Given the relatively small version difference between :autoupdate and :latest I may suggest to continue using :latest. Docker is supposed to eliminate any OS difference so yea... May be try also updating Docker just in case. I don't see much I can do from here. You may try to fiddle with it.

**Closed as completed** 2016-09-20 07:45 UTC
Labels: bug
